apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-xoy4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-xoy4
    app.kubernetes.io/part-of: ci10t-777-0079-app
  name: devfile-sample-xoy4
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-xoy4
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-xoy4
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0079-tenant/ci10t-777-0079-app/devfile-sample-xoy4@sha256:2f664db3e06ba122a9764621e82b88e6c98e69cc60d2bed4ad9d454868b5d516
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
